# Generated by Django 5.0.6 on 2024-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='con_password',
            field=models.CharField(default=12, max_length=128),
            preserve_default=False,
        ),
    ]
